#!/bin/bash

echo "🎯 GA4 추적 시스템 설정 최종 확인"
echo "================================="
echo ""
echo "✅ 완료된 작업:"
echo "  [✓] GA4 Property ID: 497433231"
echo "  [✓] Google Service Account 생성"
echo "  [✓] .env.local에 인증 정보 추가"
echo "  [✓] GA4에 Service Account 권한 부여"
echo "  [✓] Supabase 테이블 이미 생성됨"
echo ""
echo "📋 생성된 파일 확인:"
echo ""
echo "1. API 파일:"
ls -la pages/api/track-view.ts 2>/dev/null || echo "  ❌ pages/api/track-view.ts 없음"
echo ""
echo "2. 추적 스크립트:"
ls -la public/campaign-tracking.js 2>/dev/null || echo "  ❌ public/campaign-tracking.js 없음"
echo ""
echo "3. 환경변수 확인:"
grep -E "GA4_PROPERTY_ID|GOOGLE_SERVICE_ACCOUNT" .env.local | sed 's/=.*/=...설정됨.../'
echo ""
echo "================================="
echo ""
echo "🚀 다음 단계:"
echo "  1. npm run dev 실행"
echo "  2. http://localhost:3000/admin 접속"
echo "  3. 실시간 데이터 확인"
