#!/bin/bash

echo "🔧 Google Analytics 도메인 수정 가이드"
echo "====================================="
echo ""
echo "현재 문제:"
echo "- GA가 www.mas9golf.com을 추적 중 (잘못됨)"
echo "- win.masgolf.co.kr을 추적해야 함 (올바름)"
echo ""
echo "📌 해결 방법:"
echo ""
echo "1. Google Tag Manager 접속"
echo "   https://tagmanager.google.com"
echo "   GTM ID: GTM-WPBX97JG"
echo ""
echo "2. 변수(Variables) 확인"
echo "   - 좌측 메뉴에서 '변수' 클릭"
echo "   - 사용자 정의 변수 중 도메인 관련 설정 확인"
echo "   - Page Hostname 변수가 있다면 수정"
echo ""
echo "3. 태그(Tags) 확인"
echo "   - 좌측 메뉴에서 '태그' 클릭"
echo "   - GA4 구성 태그 찾기"
echo "   - 태그 클릭 후 '구성 매개변수' 확인"
echo "   - 'hostname' 또는 'page_location' 설정 확인"
echo ""
echo "4. 트리거(Triggers) 확인"
echo "   - 도메인 필터가 있는지 확인"
echo "   - mas9golf.com으로 제한된 트리거가 있다면 수정"
echo ""
echo "5. Google Analytics 4 설정"
echo "   - GA4 속성 설정 > 데이터 스트림"
echo "   - 웹 스트림 클릭"
echo "   - URL이 'www.mas9golf.com'으로 되어있다면"
echo "   - 'win.masgolf.co.kr'로 수정"
echo ""
echo "6. 수정 후 확인"
echo "   - GTM에서 '미리보기' 클릭"
echo "   - win.masgolf.co.kr 입력"
echo "   - 태그가 제대로 실행되는지 확인"
echo ""
echo "📊 GA4 데이터 스트림 URL 변경:"
echo "1. GA4 관리 > 속성 > 데이터 스트림"
echo "2. 웹 스트림 클릭"
echo "3. 스트림 URL 수정:"
echo "   변경 전: https://www.mas9golf.com"
echo "   변경 후: https://win.masgolf.co.kr"
echo ""
echo "⚠️  주의: URL 변경 후 최대 24시간까지 데이터 수집이 지연될 수 있습니다"