#!/bin/bash

echo "🎯 GA4 추적 시스템 설정 - 남은 작업"
echo "===================================="
echo ""
echo "✅ 완료된 작업:"
echo "  [✓] GA4 Property ID 확인: 497433231"
echo "  [✓] .env.local 기본 설정 완료"
echo "  [✓] 추적 스크립트 생성 (setup-ga4-tracking.sh)"
echo ""
echo "📋 남은 작업:"
echo ""
echo "1️⃣ Google Service Account 생성:"
echo "   a) https://console.cloud.google.com 접속"
echo "   b) 새 프로젝트 생성 또는 선택"
echo "   c) Google Analytics Data API 활성화"
echo "   d) Service Account 생성 (이름: masgolf-ga4-reader)"
echo "   e) JSON 키 다운로드"
echo ""
echo "2️⃣ GA4에 Service Account 권한 부여:"
echo "   a) GA4 관리 → 계정 → 계정 액세스 관리"
echo "   b) '+' 버튼 → 사용자 추가"
echo "   c) JSON의 client_email 입력"
echo "   d) 권한: '뷰어' 선택"
echo ""
echo "3️⃣ Supabase에 테이블 생성:"
echo "   database/campaign-tracking-schema.sql 실행"
echo ""
echo "4️⃣ HTML 파일에 추적 코드 추가:"
echo "   public/versions/funnel-2025-07-complete.html"
echo ""
echo "===================================="
echo ""
echo "📝 다음 명령어 실행:"
echo "   ./setup-ga4-tracking.sh"
