#!/bin/bash

echo "📊 Google Analytics 4 디버그 페이지"
echo "=================================="
echo ""
echo "🔍 GA4 데이터 추출 테스트 페이지를 만들었습니다!"
echo ""
echo "📌 접속 방법:"
echo "http://localhost:3000/ga4-debug"
echo ""
echo "✨ 디버그 페이지 기능:"
echo "1. GA4 설정 상태 확인"
echo "2. 실제 데이터 가져오기 테스트"
echo "3. 실시간 데이터 확인"
echo "4. 추출 가능한 데이터 목록 표시"
echo ""
echo "🛠️ 필요한 설정:"
echo "1. googleapis 패키지 설치"
echo "   npm install googleapis --legacy-peer-deps"
echo ""
echo "2. 환경변수 설정 (.env.local)"
echo "   - GOOGLE_SERVICE_ACCOUNT_EMAIL"
echo "   - GOOGLE_SERVICE_ACCOUNT_KEY"
echo "   - GA4_PROPERTY_ID (기본값: 497433231)"
echo ""
echo "📊 테스트 API 엔드포인트:"
echo "- /api/test-ga4 - 설정 확인"
echo "- /api/ga4-test - 간단한 데이터 테스트"
echo "- /api/ga4-campaign-metrics - 캠페인 메트릭"
echo "- /api/ga4-realtime - 실시간 데이터"
echo ""
echo "💡 팁:"
echo "브라우저 콘솔에서 직접 테스트:"
echo "fetch('/api/ga4-test').then(r => r.json()).then(console.log)"