#!/bin/bash

echo "✅ GA4 Property ID 확인 완료!"
echo "================================="
echo ""
echo "속성 ID: 497433231"
echo ""
echo "📝 .env.local에 추가할 내용:"
echo "GA4_PROPERTY_ID=497433231"
echo ""
echo "================================="
echo ""
echo "🚀 이제 Service Account를 생성해야 합니다:"
echo ""
echo "1. Google Cloud Console 접속:"
echo "   https://console.cloud.google.com"
echo ""
echo "2. 빠른 링크 (새 탭에서 열기):"
echo "   - API 활성화: https://console.cloud.google.com/apis/library/analyticsdata.googleapis.com"
echo "   - Service Account 생성: https://console.cloud.google.com/iam-admin/serviceaccounts/create"
echo ""
echo "3. Service Account 생성 단계:"
echo "   a) 서비스 계정 이름: masgolf-ga4-reader"
echo "   b) 생성 후 해당 계정 클릭"
echo "   c) '키' 탭 → '키 추가' → 'JSON' → '만들기'"
echo "   d) JSON 파일이 자동으로 다운로드됩니다"
echo ""
echo "4. GA4에 권한 부여:"
echo "   a) GA4로 돌아가서"
echo "   b) 관리 → 계정 → 계정 액세스 관리"
echo "   c) '+' 버튼 → 사용자 추가"
echo "   d) JSON 파일의 client_email 입력"
echo "   e) 권한: '뷰어' 선택"
echo "   f) 추가"
echo ""
echo "5. JSON 파일 다운로드 후:"
echo "   ./parse-service-account.sh 실행"
