#!/bin/bash

echo "🚨 보안 경고: API 키 노출!"
echo "=========================="
echo ""
echo "다음 키들이 노출되었습니다:"
echo "- OPENAI_API_KEY"
echo "- ANTHROPIC_API_KEY"
echo "- SUPABASE_SERVICE_ROLE_KEY"
echo "- POSTGRES_PASSWORD"
echo "- SLACK_WEBHOOK_URL"
echo ""
echo "🔒 즉시 취해야 할 조치:"
echo ""
echo "1. OpenAI:"
echo "   https://platform.openai.com/api-keys"
echo "   → 기존 키 삭제 → 새 키 생성"
echo ""
echo "2. Anthropic:"
echo "   https://console.anthropic.com/settings/keys"
echo "   → 기존 키 삭제 → 새 키 생성"
echo ""
echo "3. Supabase (선택사항 - 프로젝트가 중요한 경우):"
echo "   Service Role Key는 재생성이 어려우므로"
echo "   RLS 정책을 강화하는 것을 권장"
echo ""
echo "4. .gitignore 확인:"
echo "   grep '.env' .gitignore"
echo ""
echo "5. Git 히스토리 확인:"
echo "   git log --oneline -- .env.local"
echo "   (만약 커밋된 적이 있다면 BFG Repo-Cleaner 사용)"
