#!/bin/bash
# Vercel 환경 변수 설정 스크립트

echo "📋 Vercel 환경 변수 설정 가이드"
echo "================================"
echo ""
echo "1. https://vercel.com 접속"
echo "2. win.masgolf.co.kr 프로젝트 선택"
echo "3. Settings → Environment Variables"
echo ""
echo "4. 다음 환경 변수들을 모두 추가:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable: SUPABASE_SERVICE_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5eXRqdWRmdHZ2cG1jbnBwYXltdyIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE3NTE0NDcxMTksImV4cCI6MjA2NzAyMzExOX0.1X23B7AANAg_g2Q1AAYl_kIHdd_OQap8YxElvvJn1io"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable: SUPABASE_SERVICE_ROLE_KEY"  
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5eXRqdWRmdHZ2cG1jbnBwYXltdyIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE3NTE0NDcxMTksImV4cCI6MjA2NzAyMzExOX0.1X23B7AANAg_g2Q1AAYl_kIHdd_OQap8YxElvvJn1io"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable: NEXT_PUBLIC_SUPABASE_URL"
echo "Value: https://yyytjudftrvpmcnppaymw.supabase.co"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5eXRqdWRmdHZwbWNucHBheW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDcxMTksImV4cCI6MjA2NzAyMzExOX0.TxT-vnDjFip_CCL7Ag8mR7G59dMdQAKfPLY1S3TJqRE"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "5. 각 변수마다:"
echo "   - Environment: Production ✅, Preview ✅, Development ✅"
echo "   - Save 클릭"
echo ""
echo "6. 모든 변수 추가 후 자동 재배포 대기 (2-3분)"