#!/bin/bash

echo "🔧 GA4 설정 문제 해결 가이드"
echo "============================"
echo ""
echo "📌 현재 문제:"
echo "- 서비스 계정 이메일: ❌ 없음"
echo "- 서비스 계정 키: ❌ 없음"
echo ""
echo "✅ 해결 방법:"
echo ""
echo "1️⃣ .env.local 파일에 다음 추가:"
echo ""
echo "# Google Analytics 4 설정"
echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=your-service-account@your-project-id.iam.gserviceaccount.com"
echo 'GOOGLE_SERVICE_ACCOUNT_KEY="-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----"'
echo ""
echo "2️⃣ Google Cloud Console에서 서비스 계정 생성:"
echo ""
echo "1. https://console.cloud.google.com 접속"
echo "2. APIs & Services > Credentials"
echo "3. Create Credentials > Service Account"
echo "4. 이름: masgolf-ga4-reader"
echo "5. Create and Continue"
echo "6. Skip optional steps"
echo "7. Keys 탭 > Add Key > Create new key > JSON 선택"
echo "8. 다운로드된 JSON 파일 열기"
echo ""
echo "3️⃣ JSON 파일에서 복사:"
echo '- "client_email": 값을 GOOGLE_SERVICE_ACCOUNT_EMAIL에'
echo '- "private_key": 값을 GOOGLE_SERVICE_ACCOUNT_KEY에'
echo ""
echo "⚠️ 주의: private_key의 \n은 그대로 유지하세요!"
echo ""
echo "4️⃣ GA4에 권한 부여:"
echo ""
echo "1. https://analytics.google.com 접속"
echo "2. 관리 > 속성 액세스 관리"
echo "3. 사용자 추가"
echo "4. 서비스 계정 이메일 입력"
echo "5. 역할: 뷰어"
echo "6. 추가"
echo ""
echo "5️⃣ Google Analytics Data API 활성화:"
echo ""
echo "1. https://console.cloud.google.com/apis/library"
echo "2. 'Google Analytics Data API' 검색"
echo "3. Enable 클릭"
echo ""
echo "6️⃣ 서버 재시작:"
echo "npm run dev"
echo ""
echo "✅ 완료 후 http://localhost:3000/ga4-debug 에서 확인!"