#!/bin/bash

echo "🔐 Google Service Account 생성 가이드"
echo "====================================="
echo ""
echo "1. 사용자 인증 정보 유형 선택:"
echo "   → '서비스 계정' 선택"
echo ""
echo "2. 서비스 계정 세부정보:"
echo "   • 서비스 계정 이름: masgolf-ga4-reader"
echo "   • 서비스 계정 ID: masgolf-ga4-reader (자동 생성됨)"
echo "   • 설명: GA4 데이터 읽기용 서비스 계정"
echo "   → '만들기 및 계속' 클릭"
echo ""
echo "3. 역할 부여 (선택사항):"
echo "   → '건너뛰기' 클릭 (GA4에서 별도로 권한 설정)"
echo ""
echo "4. 사용자에게 액세스 권한 부여 (선택사항):"
echo "   → '완료' 클릭"
echo ""
echo "5. JSON 키 생성:"
echo "   • 생성된 서비스 계정 클릭"
echo "   • '키' 탭 클릭"
echo "   • '키 추가' → '새 키 만들기'"
echo "   • 'JSON' 선택 → '만들기'"
echo "   • JSON 파일이 자동으로 다운로드됩니다!"
echo ""
echo "====================================="
