#!/bin/bash

echo "🚀 Google Analytics 실제 데이터 연동 가이드"
echo "========================================="
echo ""
echo "현재 문제:"
echo "- 캠페인 KPI 대시보드가 더미 데이터(1,234)를 표시"
echo "- Google Analytics와 연동되지 않음"
echo ""
echo "📌 해결 방법:"
echo ""
echo "1️⃣ googleapis 패키지 설치"
echo "npm install googleapis --legacy-peer-deps"
echo ""
echo "2️⃣ 환경변수 확인 (.env.local)"
echo "필요한 환경변수:"
echo "- GOOGLE_SERVICE_ACCOUNT_EMAIL"
echo "- GOOGLE_SERVICE_ACCOUNT_KEY"
echo "- GA4_PROPERTY_ID"
echo ""
echo "3️⃣ Google Analytics 서비스 계정 설정"
echo "1. Google Cloud Console 접속"
echo "   https://console.cloud.google.com"
echo ""
echo "2. APIs & Services > Credentials"
echo ""
echo "3. 서비스 계정 키 생성:"
echo "   - Create Credentials > Service Account"
echo "   - 이름: masgolf-ga4-reader"
echo "   - Create and Continue"
echo "   - Skip optional steps"
echo "   - Keys 탭 > Add Key > Create new key > JSON"
echo ""
echo "4. JSON 파일에서 값 복사:"
echo "   - client_email → GOOGLE_SERVICE_ACCOUNT_EMAIL"
echo "   - private_key → GOOGLE_SERVICE_ACCOUNT_KEY"
echo ""
echo "5. GA4에서 권한 부여:"
echo "   - GA4 > 관리 > 속성 액세스 관리"
echo "   - 사용자 추가"
echo "   - 이메일: [서비스 계정 이메일]"
echo "   - 역할: 뷰어"
echo ""
echo "4️⃣ API 테스트"
echo "http://localhost:3000/api/ga4-campaign-metrics"
echo ""
echo "5️⃣ 자동 업데이트 설정 (선택사항)"
echo "Vercel Cron Job 또는 GitHub Actions로"
echo "매시간 API를 호출하여 데이터 업데이트"
echo ""
echo "✅ 완료되면:"
echo "- 실제 GA4 페이지뷰 데이터 표시"
echo "- 실제 사용자 수 표시"
echo "- 실제 이벤트 데이터 표시"