#!/bin/bash

echo "🔧 Supabase Service Role Key 설정 방법"
echo "===================================="
echo ""
echo "1. Supabase 대시보드에서 Service Role Key 가져오기:"
echo "   - https://supabase.com/dashboard 로그인"
echo "   - 프로젝트 선택"
echo "   - Settings → API"
echo "   - 'service_role' 키 복사 (anon key 아님!)"
echo ""
echo "2. Vercel에 환경변수 추가:"
echo "   vercel env add SUPABASE_SERVICE_KEY production"
echo "   (위에서 복사한 service_role 키 붙여넣기)"
echo ""
echo "3. 재배포:"
echo "   git commit --allow-empty -m 'Add service role key'"
echo "   git push origin main"
echo ""
echo "⚠️  주의: Service Role Key는 절대 클라이언트에 노출되면 안 됩니다!"
echo "         서버사이드(API Routes)에서만 사용하세요."
